# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=100, unique=True)),
                ('patient', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('comments', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('p_id', models.CharField(max_length=100, unique=True)),
                ('doctor', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('r_id', models.CharField(max_length=100, unique=True)),
                ('room_no', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='patient', max_length=100)),
                ('extra', models.CharField(default='Nephrology', max_length=100)),
            ],
        ),
    ]
