# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
