# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170401_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usr',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
