# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170419_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.CharField(max_length=100, unique=True)),
                ('patient', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
